project:
  type: website
  output-dir: docs/
  

website:
  title: "ЦЦИ"
  favicon: images/banner3.png
  google-analytics: "G-TNGWX5Y7FL"
  page-footer: '<p style="text-align: justify;">*© Центр ценовых индексов 2024. Все права защищены. Любое копирование, перепечатка или последующее распространение информации Центра ценовых индексов, в том числе производимое путем кэширования, кадрирования или использования аналогичных средств, запрещено без предварительного письменного согласия со стороны Центра ценовых индексов.* <br />
*Центр ценовых индексов не несет ответственности за причинение любого ущерба или убытков, возникших в связи с тем, что лицо полагалось на возможность использования Информации в определенных целях, и исключает любую другую ответственность, возникшую в связи с использованием Информации или связанную с ней.*</p>
' 
  navbar:
    title: false
    logo: images/logo.png
    background: "#1A4AFC" 
    right:
      - text: Оформить подписку
        href: subscribe.qmd
    left:
      - text: Рынки
        menu: 
          - href: pbc-index.qmd
          - href: markets/markets-oil.qmd
          - href: markets/markets-coal.qmd
          - href: markets/markets-fertilizers.qmd
          - href: markets/markets-chemicals.qmd
          - href: markets/markets-wheat.qmd
          - href: markets/markets-oilseed.qmd
          - href: markets/markets-railways.qmd
          - href: markets/markets-railways-van.qmd
          - href: markets/markets-sea-freight.qmd
          - href: markets/markets-sea-container-ports.qmd
      - text: Прогнозы
        menu: 
          - href: forecasts/forecast-fx.qmd
          - href: forecasts/forecast-gas.qmd
          - href: forecasts/forecast-fertilizers.qmd
          - href: forecasts/forecast-agro.qmd
          - href: forecasts/forecast-realty.qmd
      - text: Методология
        href: methodology.qmd
      - href: events.qmd
        text: События
      - href: about.qmd
        text: О нас
  
  sidebar:
    - id   : Рынки
      title: "Рынки"
      style: "docked"
      background: light
      contents:
        - text: "О нас"
          href: about.qmd
        - section: "Рынки"
          contents:
            - pbc-index.qmd
            - markets/markets-oil.qmd
            - markets/markets-coal.qmd
            - markets/markets-fertilizers.qmd
            - markets/markets-chemicals.qmd
            - markets/markets-wheat.qmd
            - markets/markets-oilseed.qmd
            - markets/markets-railways.qmd
            - markets/markets-sea-freight.qmd
            - markets/markets-ports.qmd
        - section: "Прогнозы"
          contents:
           - forecasts/forecast-fx.qmd
           - forecasts/forecast-gas.qmd
           - forecasts/forecast-fertilizers.qmd
           - forecasts/forecast-agro.qmd
           - forecasts/forecast-realty.qmd
        - text: "Методология"
          href: methodology.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    mainfont: "Cera"
    page-layout: article
    

editor: visual

