project:
  type: website
  output-dir: docs/

website:
  title: "CCI"
  favicon: images/banner3.png
  page-footer: '<p style="text-align: justify;">*© Центр ценовых индексов 2024. Все права защищены. Любое копирование, перепечатка или последующее распространение информации Центр ценовых индексов, в том числе производимое путем кэширования, кадрирования или использования аналогичных средств, запрещено без предварительного письменного согласия со стороны Центр ценовых индексов.* <br />
*Центр ценовых индексов не несет ответственности за причинение любого ущерба или убытков, возникших в связи с тем, что лицо полагалось на возможность использования Информации в определенных целях, и исключает любую другую ответственность, возникшую в связи с использованием Информации или связанную с ней.*</p>
' 
  navbar:
    title: false
    logo: images/logo.png
    background: "#1A4AFC"
    right:
      - text: Оформить подписку
        href: subscribe.qmd
    left:
      - text: Рынки
        menu: 
          - href: pbc-index.qmd
          - href: markets-oil.qmd
          - href: markets-coal.qmd
          - href: markets-fertilizers.qmd
          - href: markets-chemicals.qmd
          - href: markets-wheat.qmd
          - href: markets-oilseed.qmd
          - href: markets-railways.qmd
          - href: markets-sea-freight.qmd
          - href: markets-ports.qmd
      - text: Прогнозы
        menu: 
          - href: forecast-fx.qmd
          - href: forecast-gas.qmd
          - href: forecast-fertilizers.qmd
          - href: forecast-agro.qmd
          - href: forecast-realty.qmd
      - text: Методология
        href: methodology.qmd
      - href: events.qmd
        text: События
      - href: about.qmd
        text: О нас
  
  sidebar:
    - id   : Рынки
      title: "Рынки"
      style: "docked"
      background: light
      contents:
        - text: "О нас"
          href: about.qmd
        - section: "Рынки"
          contents:
            - pbc-index.qmd
            - markets-oil.qmd
            - markets-coal.qmd
            - markets-fertilizers.qmd
            - markets-chemicals.qmd
            - markets-wheat.qmd
            - markets-oilseed.qmd
            - markets-railways.qmd
            - markets-sea-freight.qmd
            - markets-ports.qmd
        - section: "Прогнозы"
          contents:
           - forecast-fx.qmd
           - forecast-gas.qmd
           - forecast-fertilizers.qmd
           - forecast-agro.qmd
           - forecast-realty.qmd
        - text: "Методология"
          href: methodology.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    mainfont: "Cera"
    page-layout: article
    

editor: visual

