---
title: "О нас"
---

**Центр ценовых индексов (ЦЦИ)** -- российское ценовое агентство. Оперативно публикуем цены на товары российского экспорта и логистику.

**Миссия Центра** обеспечить рынок репрезентативными ценовыми индикаторами. Своевременные ценовые сигналы дают экономической системе гибкость: помогают быстрее принимать решения о рисках и инвестициях.

+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Репрезентативность]{.highlight}                            | Цена - функция времени, пространства, качества товара, условий сделки. Репрезентативность ценового индекса определяется выбором наиболее типичных и рыночных условий поставки и различается для отраслей |
+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Независимость]{.highlight}                                 | Работа Центра функционально отделена от прочих подразделений Банка. Разработка методологий и контроль за их соблюдением независимы от оценки                                                             |
+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Управление конфликтом]{.highlight} [интересов]{.highlight} | Внутренние политики направлены на регулярное выявление и предотвращение конфликта интересов \|                                                                                                           |
+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Прозрачность]{.highlight}                                  | Процедура оценки основана на методологиях. Наши службы регулярно проверяют их актуальность текущим рыночным условиям                                                                                     |
+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Конфиденциальность]{.highlight}\                           | Центр соблюдает политику конфиденциальности в работе с исходными данными и источниками информации                                                                                                        |
| [и защита информации]{.highlight}                           |                                                                                                                                                                                                          |
+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
