---
title: "Данные"
toc: false
---

</p>

# Дашборды ЦЦИ

ЦЦИ предлагает своим пользователям набор аналитических дата-продуктов, которые позволяют оперативно отслеживать ключевые рынки — от экспорта энергоресурсов до динамики аграрного сектора. Дашборды дают наглядное представление о потоках, ценах и тенденциях, помогая принимать более обоснованные решения.  

## Энергетика – нефть и нефтепродукты
- [**Потоки нефти и нефтепродуктов**](https://data.pbc-index.ru/superset/dashboard/tanker-flows/) - 
  визуализация объемов и направлений морского экспорта нефти/нефтепродуктов по странам и портам.  

## Энергетика – уголь
- [**Месячный экспорт угля**](https://data.pbc-index.ru/shiny/app/coal-russia) - динамика экспорта угля по месяцам с разбивкой по направлениям и типам угля.  
- [**Недельный экспорт угля**](https://data.pbc-index.ru/shiny/app/coal-weekly) - оперативные недельные данные об экспорте угля, включая ключевые страны назначения и порты отгрузки.  
- [**Ставки фрахта на уголь**](https://data.pbc-index.ru/superset/dashboard/coal-freight/) - динамика ставок морского фрахта угля из российских портов до ключевых рынков по типам судов.  

## Энергетика – газ
- [**Глобальный рынок СПГ**](https://data.pbc-index.ru/shiny/app/global-lng) - прогноз мирового рынка СПГ до 2040 года: баланс мирового рынка, мощности, предложение по странам.  

## Аграрный сектор
- [**Уборка сельхозкультур**](https://data.pbc-index.ru/shiny/app/agro-uborka) - ход уборочной кампании: площади, объемы уборки по основным культурам, динамика по регионам.  
- [**Cев сельхозкультур**](https://data.pbc-index.ru/shiny/app/agro-sev) - мониторинг посевной кампании: площади по основным культурам, динамика по регионам.  
  


