---
title: "События"
toc: false
---

### ЦЦИ запустил Котировку соевого шрота 

19 Февраля 2026 г.

Центр ценовых индексов (ЦЦИ) начал рассчитывать ежемесячные котировки на соевый шрот (массовая доля сырого протеина - более 50%) на базисе FCA ЦФО. Котировки публикуются с января 2026 г. в ежемесячном отчете, который выходит каждую вторую среду месяца. 

[Пресс-релиз →](events/2026-02-19-soybeans.qmd)

### Металлы потеснили ТЭК: ЦЦИ обновил методологию Сырьевого индекса ЦЦИ в ответ на сдвиг в структуре российского экспорта

4 Февраля 2026 г.

Центр ценовых индексов (ЦЦИ) представил обновленную версию Сырьевого индекса ЦЦИ. Снижение доли энергетического экспорта РФ до минимума за 5 лет потребовало увеличения представленности в индексе товаров неэнергетического экспорта.

[Пресс-релиз →](events/2026-02-04-commodity-index.qmd)

### Презентация Контейнерного индекса ЦЦИ

22 октября 2025 г.

-   Почему ставки на контейнерные перевозки так волатильны?
-   Как Контейнерный индекс ЦЦИ отражает реалии российского логистического рынка и соотносится с мировыми индексами?
-   О стоимости логистики как об универсальном индикаторе спроса в экономике

[Материалы →](events/2025-10-22-container-index.qmd)

### Что происходит в экономике России и мира и как узнавать об этом раньше всех? Говорят аналитики ЦЦИ и ГПБ

11 сентября 2025 г.

-   Повлияли ли тарифы Д.Трампа на мировую торговлю и спрос? Можем ли мы сделать какие-то выводы?
-   Снижение внешнего спроса для России никак не отражается на курсе рубля – почему? Стал ли рубль фундаментально крепче?
-   Россия сталкивается со слабым внешним и внутренним спросом. Нет ли ощущения что монетарная политика будет смягчаться быстрее ожиданий?
-   Слабый спрос и крепкий рубль – выручка российских компаний под давлением. Нет ли рисков для финансовой стабильности.

[Материалы →](events/2025-09-11-cbonds.qmd)

### Пятница с ЦЦИ : Сложное время для рынка угля

6 июня 2025 г.

-   Валютный курс, который в 1 кв. 2025 г. привел экспортные нетбэки в отрицательную зону. Что ожидать дальше?
-   Угольный кризис только для угольных компаний? Что происходит на рынке ж/д перевозок угля?
-   Рост добычи Китая и Индии и ценообразование в Индонезии
-   Все ли так однозначно с точки зрения перспектив угля и совладает ли логика экспертов с логикой потребителей?

[Материалы →](events/2025-06-06-coal.qmd)

### Пятница с ЦЦИ : Агропромышленность

6 июня 2025 г.

-   Влияние тарифного противостояния на рынок АПК
-   Прогнозы урожая и экспорта российской агропродукции в 2025/2026
-   Ключевые рынки сбыта для российского АПК
-   Динамика экспортных цен на агропродукцию
-   Технологические аспекты морского фрахта растительных масел

[Материалы →](events/2025-06-06-agro.qmd)

### Пятница с ЦЦИ: газ и химия

31 марта 2025

-   Газовый ТРАМПлин в США
-   Газовый рынок Европы показал признаки жизни?
-   Азия: Азотный суверенитет требует больше газа

[Материалы вебинара](events/2025-03-21-gas.qmd)

### Пятница с ЦЦИ: логистика

07 февраля 2025

-   Как российские нефть, уголь, зерно, удобрения попадают на мировые рынки и сколько это стоит?
-   Какова доля логистических затрат в конечной стоимости товара?
-   Почему уголь на Дальний Восток везти дорого, а продукты питания едут туда за бесплатно?
-   Кто в логистическом секторе может занести год себе в актив, а кто мечтает о переменах?

[Материалы вебинара](events/2025-02-07-logistics.qmd)

### Пятница с ЦЦИ: уголь

25 октября 2024

-   Состояние мировой экономики и меры экономической поддержки Китая
-   Экспортные рынки углей и цены на уголь
-   Рынки полувагонов и нетбэки на уголь

[Материалы вебинара](events/2024-10-25-coal.qmd)

### Пятница с ЦЦИ: корабли с черным золотом

13 сентября 2024

-   Особенности морского путешествия российской нефти
-   Сколько стоит круиз от Балтики до Китая?
-   Логистика = дисконт?

[Материалы вебинара](events/2024-09-13-crude.qmd)

### Пятница с ЦЦИ: хлеб с маслом

13 сентября 2024

-   Прогнозы урожая и экспорта зерна в 2024/25 г.
-   Куда плывут российские подсолнечное масло и пшеница
-   Как чувствуют себя импортеры российских агротоваров: диагноз макроэкономиста
-   Прогноз погоды на рынке морского фрахта зерна

[Материалы вебинара](events/2024-09-13-wheat.qmd)

### Пятница с ЦЦИ: газ

31 мая 2024

-   Почему снижаются цены на газ в мире?
-   Что происходит на газовом рынке США?
-   СПГ перетекает из Европы в Азию?
-   Станет ли Индия новым драйвером спроса на СПГ?

[Материалы вебинара](events/2024-05-31-gas.qmd)

### Пятница с ЦЦИ: уголь

31 мая 2024

-   Уголь теперь дешевый? Кто поддерживает спрос, а кто давит объёмами?
-   ЕС и Турция. Закат и возрождение угля.
-   Идем на Восток. Чего ждать от Китая и Индии?
-   Как начинает 2024 г. российский экспорт?

[Материалы вебинара](events/2024-05-31-coal.qmd)

### Презентация Сырьевого индекса ЦЦИ

27 мая 2024

[Материалы вебинара](events/2024-05-27-PBC-index.qmd)

### Пятница с ЦЦИ: газ

9 февраля 2024

-   Деглобализация и высокие процентные ставки для экспортеров газа
-   Предложение и спрос на газ в мире
-   Бенчмарки мировых цен на газ

[Материалы вебинара](events/2024-02-09-gas.qmd)
