---
title: "Методология ценовых индикаторов"
lang: ru
toc: true
format: 
   typst:
      mainfont: "CeraCY"
      font-paths: fonts/
      number-sections: false
      columns: 1
   

---

### [**Введение**]{style="color:#1b4afc"}

Данная методология подробно описывает принципы работы Центра ценовых индексов при оценке и формировании ценовых индикаторов на товарно-сырьевых рынках. Основной целью Центра ценовых индексов является публикация достоверных и репрезентативных ценовых индикаторов, отражающих ситуацию на товарно-сырьевых рынках. При определении ценовых индикаторов Центр ценовых индексов стремится учитывать принятую в отрасли практику. Независимость и беспристрастность лежит в основе деятельности Центра ценовых индексов, который не имеет финансовой заинтересованности в публикуемой информации.

### [Порядок сбора информации]{style="color:#1b4afc"}

Сбор информации осуществляется регулярно на основе опроса участников рынка, в соответствии с внутренними регламентами сбора, проверки, анализа и хранения ценовой информации. Центр ценовых индексов получает информацию из всех надежных источников. Сотрудники Центра ценовых индексов постоянно стремятся увеличивать число компаний и респондентов, расширяя базу контактов. Число компаний, готовых предоставлять информацию о рынке, может варьироваться в зависимости от ситуации на рынке. Сбор информации осуществляется по телефону, электронной почте, с помощью общедоступных систем мгновенного обмена сообщениями.

Центр ценовых индексов старается удовлетворить коммуникационные потребности участников рынка и стремится открывать любые дополнительные необходимые каналы связи.

### [Проверка источников информации]{style="color:#1b4afc"}

В процессе сбора информации сотрудники Центра ценовых индексов взаимодействуют с различными участниками рынка и поставщиками данных (далее - «источники информации»). В рамках стандартной практики контроля качества и проверки достоверности данных, используемых для формирования ценовых индикаторов, Центр ценовых индексов регулярно осуществляет проверку поставщиков данных, участвующих в опросе для определения итогового ценового индикатора. В рамках процедуры проверки источника информации, Центр ценовых индексов может оценивать:

-   Репутацию источника информации;
-   Размер и долю участия источника информации в операциях на рынке;
-   Способность источника информации своевременно предоставлять актуальную и достоверную ценовую информацию;
-   Возможности Центра ценовых индексов верифицировать предоставленную информацию с другими источниками информации.

Центр ценовых индексов призывает участников рынка раскрывать и предоставлять все данные, которые могут иметь отношение к формированию ценового индикатора.

### [Проверка ценовой информации]{style="color:#1b4afc"}

В основе принципов работы Центра ценовых индексов лежит принцип прозрачности оценки и публикации ценовых индикаторов. Сотрудники Центра ценовых индексов проверяют всю информацию, поступающую от участников рынка. Первостепенное внимание уделяется к полностью проверяемой и прозрачной информации. В обязанности сотрудников Центра ценовых индексов входит проведение тщательного анализа собранных данных и их верификация. Сотрудниками Центра ценовых индексов осуществляется первичная проверка данных, а затем устанавливается целесообразность их дальнейшей более детальной верификации. Центр ценовых индексов использует различные методы для подтверждения достоверности и качества данных, включая перекрестные проверки, а также запросы подтверждающей документации и инициирование дополнительного взаимодействия с вышестоящим руководством компании, от которой были получены сведения, подлежащие верификации. Осуществляется дополнительный экспертный анализ и учет решений об исключении нестандартных и нерепрезентативных сделок. В случае выявления нетипичных для рынка сделок и цен Центр ценовых индексов исключает данные, которые не могут быть верифицированы на рынке в той мере, в которой это считается целесообразным.

### [Порядок обращения с нестандартными и нерепрезентативными данными]{style="color:#1b4afc"}

Центр ценовых индексов определяет нестандартные и нерепрезентативные данные, как любую информацию, которая не соответствует или отклоняется от методологии или стандартных рыночных условий. Сделки, совершенные по ценам, находящимся значительно ниже или выше уровня цен, преобладающих на рынке цен, считаются нетипичными. Сделки, которые считаются нетипичными для рынка и искажающими рыночный уровень цен, исключаются из оценки.

### [Условия типовых контрактов]{style="color:#1b4afc"}

Ценовые индикаторы, публикуемые Центром ценовых индексов, отражают стандартные условия контрактов на общепринятых базисах торговли, в соответствии со стандартной отраслевой практикой. Цены приводятся в соответствие со стандартными определениями, что позволяет получить репрезентативную окончательную оценку. Центр ценовых индексов сопоставляет данные, собранные посредством анализа рынка со стандартными спецификациями.

### [Методика расчета ценовых индикаторов]{style="color:#1b4afc"}

Ценовые индикаторы рассчитываются, как среднее арифметическое значение подтвержденных рыночных сделок, попавших в рыночный диапазон ответов. Сделка - это информация о рыночной котировке, данные которой подтверждены со стороны покупателя и продавца, или информация о результатах публичных торгов. Котировка - ответ участника рынка о наблюдаемом уровне цен на рынке, который удовлетворяет оценке рыночного диапазона котировок. Рыночный диапазон котировок - это все ответы участников рынка, кроме выбросов, не входящих в 97,5% доверительный интервал нормального распределения. Использование принципа усреднения на основе метода средне арифметических величин обусловлено подходом к минимизации влияния субъективных факторов в оценке, а также базовыми положениями экономической теории к понятию рыночных условий сделки, предполагающих равный доступ участников рынка.
Использование рыночного диапазона в расчете индекса позволяет очистить опросные данные от аномальных значений и учитывать исключительно непротиворечивые и достоверные данные о рыночных ценах.

### [Корректировка данных]{style="color:#1b4afc"}

В случае необходимости исправления ошибочного значения ценового индикатора, возникшего вследствие технических сбоев, человеческой ошибки или некорректного применения принятой методологии, Центр ценовых индексов оставляет за собой право скорректировать данные. Данные также могут быть скорректированы в случае исправления ошибок, возникших в результате сообщения участниками рынка не точной информации о сделках на рынке. Центр ценовых индексов информирует участников рынка о случаях корректировки данных.

### [Принципы формирования методологии и внесения изменений]{style="color:#1b4afc"}

Методологии разрабатываются и утверждаются независимым от блока оценки методологическим комитетом, который состоит из сотрудников, обладающих достаточным уровнем квалификации и профессиональным опытом. В целях обеспечения актуальности, осуществляется ежегодная оценка соответствия методологии специфике рынка, необходимости упразднения неактуальных или создания новых ценовых индикаторов. Центр ценовых индексов приветствует диалог с участниками рынка по вопросам методики, применяемой для оценки и формирования ценовых индикаторов. Обновление методологии подразумевает подробное объяснение предлагаемых изменений и их обоснование. Об изменении сообщается в соответствующем информационном продукте, также указывается дата, с которой изменения вступают в силу.

### [Порядок хранения и использования информации]{style="color:#1b4afc"}

Центр ценовых индексов документирует и хранит: - Исходные данные, используемые при формировании ценового индикатора; - Методологии, используемые при формировании ценового индикатора; - Факты применения суждений аналитиками при формировании ценового индикатора, включая обоснование применения суждений; - Факты исключения из оценки ценового индикатора исходных данных, включая обоснование подобных исключений.

### [Конфиденциальность данных]{style="color:#1b4afc"}

Центр ценовых индексов придает большое значение обеспечению безопасности и защите информации, а также гарантирует полную конфиденциальность данных, получаемых от участников рынка.



Продукт и его характеристики

+---------------------------------+--------------------------------------------+
| Параметры                       | Характеристика                             |
+=================================+============================================+
| Russian Standard LV Low Sulfu   | Зольность не более 11%, Ro - 1-1,69,       |
|                                 |                                            |
|                                 | VM - 17-25%, Y - 13-17 мм; CSR - 40-45;    |
|                                 |                                            |
|                                 | Сера - ≤0,4%; Влажность - не более 13%.    |
+---------------------------------+--------------------------------------------+
| Russian Standard Fat Low Sulfur | Зольность не более 11%, Ro - 0,8-1,19,\    |
|                                 | VM - 28-36%, Y - 14-18 мм; CSR - 40-45;\   |
|                                 | Сера - ≤0,4%; Влажность - не более 13%.    |
+---------------------------------+--------------------------------------------+
| Russian Primary Fat Low Sulfur  | Зольность не более 11%, Ro - 0,8-1,19,\    |
|                                 | VM - 28-36%, Y до 30 мм; CSR - 50-60;\     |
|                                 | Сера - ≤0,4%; Влажность - не более 13%.    |
+---------------------------------+--------------------------------------------+
| Russian Semi-soft               | Зольность не более 11%, Ro - 1,1-1,69,\    |
|                                 | VM - \<30%, Y - 6-12 мм;\                  |
|                                 | Сера - менее 1%; Влажность - не более 13%. |
+---------------------------------+--------------------------------------------+
| Russian Kuzbass Gas Fat         | Зольность не более 11%, Ro - 0,5-0,99,\    |
|                                 | VM - 31-38%, Y - 16-25 мм;\                |
|                                 | Сера - менее 1%; Влажность - не более 13%  |
+---------------------------------+--------------------------------------------+
| Russian PCI LV                  | Зольность не более 11%, VM - 10-15%,\      |
|                                 | Сера - 0,4%; Влажность - не более 11%.     |
+---------------------------------+--------------------------------------------+
| Russian PCI MV                  | Зольность не более 11%, VM - 18-23%,\      |
|                                 | Сера - 0,3-0,5%; Влажность - не более 11%. |
+---------------------------------+--------------------------------------------+
