---
title: "Методология ценовых индикаторов"
lang: ru
toc: true
---

### Введение

Данная методология подробно описывает принципы работы Центра ценовых индексов при оценке и формировании ценовых индикаторов на товарно-сырьевых рынках.

Основной целью Центра ценовых индексов является публикация достоверных и репрезентативных ценовых индикаторов, отражающих ситуацию на товарно-сырьевых рынках.

При определении ценовых индикаторов Центр ценовых индексов стремится учитывать принятую в отрасли практику. Независимость и беспристрастность лежит в основе деятельности Центра ценовых индексов, который не имеет финансовой заинтересованности в публикуемой информации.

### Порядок сбора информации

Сбор информации осуществляется регулярно на основе опроса участников рынка и мониторинга публичной информации, в соответствии с внутренними регламентами сбора, проверки, анализа и хранения ценовой информации.

Центр ценовых индексов получает информацию из всех надежных источников. Сотрудники Центра ценовых индексов постоянно стремятся увеличивать число компаний и респондентов, расширяя базу контактов. Число компаний, готовых предоставлять информацию о рынке, может варьироваться в зависимости от ситуации на рынке.

Сбор информации осуществляется по телефону, электронной почте, с помощью систем мгновенного обмена сообщениями.

Центр ценовых индексов старается удовлетворить коммуникационные потребности участников рынка и стремится открывать любые дополнительные необходимые каналы связи.

### Проверка источников информации

Центр ценовых индексов осуществляет проверку источников информации, участвующих в опросе или используемых для определения ценового индикатора. В рамках процедуры проверки источника информации Центр ценовых индексов предъявляет следующие требования:

- Участие источника информации в операциях на рынке. Источником информации могут быть взаимозависимые компании, при условии, что одна из них удовлетворяет требованиям по участию в операции на рынке. Проверка осуществляется на основании открытых данных и/или данных, предоставленных самим источником информации;
- Представитель организации-источника информации в приоритете представляет функции бэк-офиса;
- Способность на регулярной основе предоставлять актуальную и достоверную ценовую информацию;
- Репутация источника. Необходимо отсутствие публичной информации о манипуляциях рынка;
- Согласие придерживаться правил профессиональной этики Центра ценовых индексов: в письменных ответах и устной коммуникации с аналитиками не пытаться манипулировать рыночной информацией; не затрагивать темы национальностей, религии, политических взглядов, гендерных и возрастных различий; не использовать нецензурные выражения.

Проверка источника информации на соответствие требованиям осуществляется в момент первого опроса или иного способа получения информации и далее осуществляется с ежегодной периодичностью.

Центр ценовых индексов призывает участников рынка раскрывать и предоставлять все данные, которые могут иметь отношение к формированию ценового индикатора. \### Проверка ценовой информации

В основе принципов работы Центра ценовых индексов лежит принцип прозрачности оценки и публикации ценовых индикаторов. Сотрудники Центра ценовых индексов проверяют всю информацию, поступающую от участников рынка. Первостепенное внимание уделяется к полностью проверяемой и прозрачной информации.

В обязанности сотрудников Центра ценовых индексов входит проведение тщательного анализа собранных данных и их верификация. Сотрудниками Центра ценовых индексов осуществляется первичная проверка данных, а затем устанавливается целесообразность их дальнейшей более детальной верификации.

Центр ценовых индексов использует различные методы для подтверждения достоверности и качества данных, включая перекрестные проверки, а также запросы подтверждающей документации и инициирование дополнительного взаимодействия с вышестоящим руководством компании, от которой были получены сведения, подлежащие верификации.

### Порядок обращения с нестандартными и нерепрезентативными данными

Центр ценовых индексов определяет нестандартные и нерепрезентативные данные, как любую информацию, которая не соответствует или отклоняется от методологии или стандартных рыночных условий.

Сделки и наблюдения, которые считаются нестандартными и нерепрезентативными, не используются в расчете ценового индикатора, если не принято решение о сохранении таких данных в расчете.

Для вынесения суждения о сохранении нестандартных или нерепрезентативных данных привлекается экспертный совет не менее трех человек из состава аналитиков блока оценки и службы методологии и внутреннего контроля (далее - Экспертный совет).

### Условия типовых контрактов

Ценовые индикаторы, публикуемые Центром ценовых индексов, отражают стандартные условия контрактов на общепринятых базисах торговли, в соответствии со стандартной отраслевой практикой.

Цены приводятся в соответствие со стандартными определениями, что позволяет получить репрезентативную окончательную оценку.

Центр ценовых индексов сопоставляет данные, собранные посредством анализа рынка со стандартными спецификациями.

### Методика расчета ценовых индикаторов

Ценовые индикаторы рассчитываются, как среднее арифметическое значение наблюдений и подтвержденных рыночных сделок, попавших в рыночный диапазон ответов. Полученный таким образом ценовой индикатор считается установленный опросным путем.

*Сделка* - это информация о рыночной котировке, данные которой подтверждены со стороны покупателя и продавца, или информация о результатах публичных торгов.

*Наблюдение* - ответ участника рынка о наблюдаемом уровне цен на рынке.

*Рыночный диапазон* - это все ответы участников рынка и информация о сделках, кроме выбросов, не входящих в 95% доверительный интервал распределения Стьюдента.

Использование принципа усреднения на основе метода среднеарифметических величин обусловлено подходом к минимизации влияния субъективных факторов в оценке, а также базовыми положениями экономической теории к понятию рыночных условий сделки, предполагающих равный доступ участников рынка.

Использование рыночного диапазона в расчете индекса позволяет очистить опросные данные от аномальных значений и учитывать исключительно непротиворечивые и достоверные данные о рыночных ценах.

### Порядок расчета ценовых индикаторов при недостаточности данных

В случае снижения количества сделок и наблюдений на рынке (например, при значительном сокращении экспорта) их количество может оказаться недостаточным для определения репрезентативного ценового показателя. В таких условиях ценовой индикатор считается неустановленным опросным путем.

При невозможности установить ценовой индикатор опросным путем Центр ценовых индексов продолжит устанавливать ценовой индикатор с помощью дополнительной информации об альтернативных ценах на наблюдаемом рынке, предоставленную организациями-источниками информации, а также содержащуюся в иных источниках, позволяющую установить репрезентативное значение ценового индикатора. 

В приоритете используется информация об альтернативных ценах, полученная от организаций-источников информации. При ее отсутствии – в иных источниках. Ко всем организациям-источникам информации применяются требования и осуществляется контроль соответствия требованиям, аналогичным отраженным в разделах «Порядок сбора информации», «Проверка источников информации» и «Проверка исходных данных»

К иным источникам информации Центр ценовых индексов предъявляет следующие требования:

-	Регулярное обновление информации.
Наличие в материалах источника данных за предыдущие периоды с периодичностью не менее 1 раза в месяц.
-	Наличие ценовых данных о соответствующем товарном рынке. 
Наличие в материалах источника индикаторов, отражающих цены на соответствующем товарном рынке на других распространенных базисах.
-	Хранение исторических данных.
Наличие в материалах источника данных за предыдущие периоды с глубиной ретроспективы не менее 1 года.
-	Использование источника участниками соответствующего товарного рынка. 
-	Независимость от участников соответствующего товарного рынка. 

Источник представляет собой агрегатор данных, биржу или другое ценовое агентство. Представленные в ресурсах источника ценовые индикаторы сопровождаются методологией.

Проверка соответствия иного источника информации об альтернативных ценах требованиям осуществляется в момент его первого использования.

Альтернативные цены – это:
-	Данные о ценах на товары иного качества или базиса поставки, которые могут быть использованы для оценки стоимости товара с учетом коэффициентов логистики и качества;
-	Данные о ценах на товары-заменители, сырье для производства товара или продуктах его переработки, динамика которых может быть использована для оценки динамики изменения стоимости товара. 

Для вынесения суждения о репрезентативности установленного с помощью альтернативных цен значения ценового индикатора привлекается Экспертный совет. Установленный с помощью альтернативных цен ценовой индикатор не маркируется при публикации в случае, если использование альтернативных цен не связано с существенным изменением предпосылок расчета ценового индикатора.

Значительные стрессовые события на рынке, такие как правительственный запрет на экспорт, введение заградительных импортных пошлин или торговых эмбарго на экспортных рынках, нарушения логистических цепочек и другие причины, могут приводить к сильному изменению альтернативных цен и невозможности установить репрезентативный ценовой индикатор на их основании без существенного изменения предпосылок расчета. 

В таких случаях, по возможности, в качестве значения ценового индикатора будет использоваться альтернативный показатель, предпосылки расчета которого отличаются от стандартных предпосылок расчета ценового индикатора, но который по мнению аналитиков 
ЦЦИ достоверно и репрезентативно отражает ситуацию на анализируемом товарно-сырьевых рынке. Для вынесения суждения о достоверности и репрезентативности отражения альтернативным индикатором рыночной ситуации привлекается Экспертный совет. 
Установленный с помощью такого способа ценовой индикатор будет маркироваться при публикации с раскрытием применяемых предпосылок расчета альтернативного показателя.

Если Экспертный совет приходит к выводу о нерепрезентативности установленного с помощью альтернативных цен значения ценового индикатора, то значение ценового индикатора устанавливается на предыдущем уровне с маркировкой при публикации. 

### Порядок приостановки или прекращения предоставления ценового индикатора 

В случае невозможности определения ценового индикатора или в случае нерепрезентативности значения ценового индикатора, полученного с помощью альтернативных цен, в течение 2 и более последовательных периодов, Центр ценовых индексов может приостановить формирование ценового индикатора и сбор исходных данных до изменения ситуации (например, снятия запрета на экспорт) и появления новой информации, которая позволит сформировать репрезентативное значение ценового индикатора. Решение о приостановке формирования ценового индикатора принимается Экспертным советом, о приостановке сообщается в соответствующем информационном продукте.

Центр ценовых индексов оставляет за собой право прекратить публикацию и расчет ценового индикатора. Решение о прекращении предоставления и расчета ценового индикатора принимается Экспертным советом и утверждается высшим исполнительным органом Центра ценовых индексов. Процесс прекращения предоставления и расчета ценового индикатора сопровождается поэтапными уведомлениями о рисках и последующем фактическом прекращении публикации ценового индикатора:

1.	уведомление в очередной публикации ценового индикатора о возможном будущем прекращении публикации индикатора с указанием предполагаемой даты прекращения публикации (не менее чем за 1 месяц до прекращения публикации);
2.	уведомление организаций-источников информации и публичных пользователей ценового индикатора о начале консультаций и сбора обратной связи с рынка;
3.	анализ обратной связи и выработка дальнейшего решения в виде прекращения публикации ценового индикатора или прекращения публикации ценового индикатора и разработки новой альтернативы, приемлемой для участников рынка;
4.	окончательное уведомление о прекращении публикации ценового индикатора; 
5.	исключение ценового индикатора из перечня ценовых индикаторов Центра ценовых индексов и прекращение работ по сбору информации. Сохранение архива исторических данных в публичном доступе.

### Пересмотр значений ценового индикатора

В случае необходимости исправления ошибочного значения ценового индикатора, возникшего вследствие технических сбоев, человеческой ошибки или некорректного применения принятой методологии, Центр ценовых индексов пересматривает значение ценового индикатора. Исправлению подлежат данные с датой публикации давностью не более 1 года от момента обнаружения ошибки. 

Получение после окончания периода сбора данных дополнительной информации о наблюдениях или сделках не приводит к пересмотру значения ценового индикатора. 

Порядок пересмотра исторических значений ценового индикатора:
-	Повторение расчетной процедуры на истекшую дату на основании исправленной выборки исходных данных и/или исправленных процессов применения методологии;
-	Фиксирование исправленного значения ценового индикатора и факта корректировки в исторических данных во внутренних системах хранения информации;
-	Внесение изменений в публикацию ценового индикатора за истекшую дату;
-	Публикация сообщения о произошедшей корректировке с указанием причины.

Центр ценовых индексов информирует участников рынка о случаях корректировки данных.

### Принципы формирования методологии и внесения изменений

Методологии разрабатываются и утверждаются независимым от блока оценки методологическим комитетом, который состоит из сотрудников, обладающих достаточным уровнем квалификации и профессиональным опытом.

В целях обеспечения актуальности, осуществляется ежегодная оценка соответствия методологии специфике рынка, необходимости упразднения неактуальных или создания новых ценовых индикаторов.

Центр ценовых индексов приветствует диалог с участниками рынка по вопросам методики, применяемой для оценки и формирования ценовых индикаторов. 

Обновление методологии подразумевает подробное объяснение предлагаемых изменений и их обоснование. 
Об изменении сообщается в соответствующем информационном продукте, также указывается дата, с которой изменения вступают в силу.

### Порядок хранения и использования информации

Центр ценовых индексов документирует и хранит:

-	Исходные данные, используемые при формировании ценового индикатора;
-	Методологии, используемые при формировании ценового индикатора;
-	Факты применения суждений аналитиками при формировании ценового индикатора, включая обоснование применения суждений;
-	Факты исключения из оценки ценового индикатора исходных данных, включая обоснование подобных исключений.

### Конфиденциальность данных

Центр ценовых индексов придает большое значение обеспечению безопасности и защите информации, а также гарантирует полную конфиденциальность данных, получаемых от участников рынка.
