---
title: "Методология консенсус-прогноза"
lang: ru
toc: true
title-block-banner: none
fig-format: svg
---

# Методология консенсус-прогноза (Опрос профессиональных аналитиков)

## Основные положения

### Введение

Данная методология подробно описывает принципы работы Центра ценовых индексов при формировании консенсус-прогнозов индикаторов в опросах профессиональных аналитиков.

Основной целью Центра ценовых индексов является публикация достоверных и репрезентативных консенсус-прогнозов, отражающих ожидания профессионального сообщества.

При определении консенсус-прогнозов Центр ценовых индексов стремится учитывать принятую в отрасли практику.

Независимость и беспристрастность лежит в основе деятельности Центра ценовых индексов, который не имеет финансовой заинтересованности в публикуемой информации.

### Порядок сбора информации

Сбор информации осуществляется сотрудниками Центра ценовых индексов либо с привлечением третьих лиц на основе опроса участников рынка в соответствии с внутренними регламентами сбора, проверки, анализа и хранения конфиденциальной информации. 

Центр ценовых индексов получает информацию из всех надежных источников. Сотрудники Центра ценовых индексов постоянно стремятся увеличивать число компаний и респондентов, расширяя базу контактов. Число аналитиков, готовых предоставлять информацию, может варьироваться в зависимости от ситуации в экономике.

Сбор информации осуществляется по телефону, электронной почте, с помощью общедоступных систем мгновенного обмена сообщениями, а также автоматических средств коммуникации, разработанных на базе платформ Центра ценовых индексов.

Центр ценовых индексов старается удовлетворить коммуникационные потребности участников рынка и стремится открывать любые дополнительные необходимые каналы связи.

### Проверка источников информации

В процессе сбора информации сотрудники Центра ценовых индексов взаимодействуют с различными аналитиками и поставщиками данных (далее - «источники информации»).

В рамках стандартной практики контроля качества и проверки достоверности данных, используемых для формирования консенсус-прогноза, Центр ценовых индексов регулярно осуществляет проверку поставщиков данных, участвующих в опросе для определения итогового консенсус-прогноза.

В рамках процедуры проверки источника информации, Центр ценовых индексов может оценивать:

-   Репутацию источника информации;
-   Способность источника информации своевременно предоставлять актуальную и непротиворечивую информацию.

Центр ценовых индексов призывает участников опроса предоставлять все данные, которые могут иметь отношение к формированию консенсус-прогноза.

### Проверка поступающей информации

В основе принципов работы Центра ценовых индексов лежит принцип прозрачности оценки и публикации консенсус-прогноза.

Сотрудники Центра ценовых индексов проверяют всю информацию, поступающую от поставщиков данных.

В обязанности сотрудников Центра ценовых индексов входит проведение тщательного анализа собранных данных и их верификация.

Сотрудниками Центра ценовых индексов осуществляется первичная проверка данных, а затем устанавливается целесообразность их дальнейшего использования.

### Методика обработки информации

Результаты опроса представляются в агрегированном и обезличенном виде.

Для каждого из представленных в опросе и приведенных в спецификации индикаторов могут публиковаться следующие агрегированные данные: медиана, выборочное среднее, максимум и минимум, 25% и 75%-перцентили. 

Медиана – серединное значение ответов респондентов, 50% ответов больше или равны медиане, другие 50% ответов меньше или равны медиане.

Среднее – простое среднее арифметическое ответов респондентов.

25% и 75% перцентили – границы диапазона, не включающего 25% минимальных и 25% максимальных ответов респондентов.

Использование медианы и среднего позволяет более полно описать распределение ответов аналитиков и предоставить наиболее репрезентативные результаты в консенсус-прогнозе.

Использование перцентилей позволяет очистить опросные данные от аномальных значений, не являющихся наиболее распространенными по результатам опроса.

### Корректировка данных

В случае необходимости исправления ошибочного значения консенсус-прогноза, возникшего вследствие технических сбоев, человеческой ошибки или некорректного применения принятой методологии, Центр ценовых индексов оставляет за собой право скорректировать данные.

Данные также могут быть скорректированы в случае исправления ошибок, возникших в результате сообщения участниками опроса неточной информации.

### Принципы формирования методологии и внесения изменений

Методологии разрабатываются и утверждаются независимым от прочих подразделений методологическим комитетом, который состоит из сотрудников, обладающих достаточным уровнем квалификации и профессиональным опытом.

В целях обеспечения актуальности, осуществляется ежегодная оценка соответствия методологии, необходимости упразднения неактуальных или создания новых опросных индикаторов.

Центр ценовых индексов приветствует диалог с участниками опроса по вопросам методики, применяемой для оценки и формирования индикаторов. Обновление методологии подразумевает подробное объяснение предлагаемых изменений и их обоснование.

Об изменении сообщается в соответствующем информационном продукте, также указывается дата, с которой изменения вступают в силу.

### Порядок хранения и использования информации

Центр ценовых индексов документирует и хранит:

-   Исходные данные, используемые при формировании консенсус-прогноза;
-   Дополнительные сведения, предоставляемые респондентами в рамках регулярных опросов.
-   Методологии, используемые при формировании консенсус-прогноза;
-   Результаты агрегированных данных консенсус-прогноза в соответствии с данной методологией.

### Конфиденциальность данных

Центр ценовых индексов придает большое значение обеспечению безопасности и защите информации, а также гарантирует полную конфиденциальность данных, получаемых от участников опроса.

В списке участников опроса указываются только регулярно участвующие и отдельно подтвердившие свое согласие в данной форме аналитики.
