---
title: "Методология валютных курсов"
lang: ru
toc: true
title-block-banner: none
fig-format: svg
---

# Методология: валютные курсы

## Основные положения

### Введение

Данная методология подробно описывает принципы работы Центра ценовых индексов при определении курсов иностранных валют, используемых для оценки ценовых индикаторов на товарно-сырьевых рынках в альтернативных валютах, отличных от оригинальных.

Основной целью Центра ценовых индексов является публикация достоверных и репрезентативных ценовых индикаторов, отражающих ситуацию на товарно-сырьевых рынках.

При определении ценовых индикаторов в альтернативных валютах Центр ценовых индексов стремится учитывать принятую в отрасли практику.

Независимость и беспристрастность лежит в основе деятельности Центра ценовых индексов, который не имеет финансовой заинтересованности в публикуемой информации.

### Порядок сбора информации

Сбор информации о курсах валют осуществляется регулярно с ежедневной периодичностью в соответствии с внутренними регламентами сбора, проверки, анализа и хранения ценовой информации.

Сбор информации осуществляется с помощью сети Интернет и автоматизированных систем, разработанных на базе платформ Центра ценовых индексов.

### Общий порядок определения курсов валют

При обозначении курсов валютных пар Центр ценовых индексов использует стандарт Международной организации по стандартизации (ISO 4217) – трехбуквенная аббревиатура названия валюты. Для разделения базовой и встречной валюты используется slash-знак.

Например, «USD/RUB» – количество российских рублей, которое можно купить за один доллар США, где базовая валюта – доллар США, встречная валюта – российский рубль. В обратном случае «RUB/USD» - количество долларов США, которое можно купить за один российский рубль.

Произведение данных обратных валютных пар USD/RUB и RUB/USD и любых других обратных валютных пар равно единице (1), округленной до пяти знаков.

Основным источником информации о курсах иностранных валют выступают ежедневные официальные данные Банка России о курсах иностранных валют к российскому рублю.

### Порядок обращения к альтернативным источникам

Отдельные валютные пары неликвидны и их курс к российскому рублю не рассчитывается и не публикуется Банком России регулярно с ежедневной периодичностью.

В таких случаях источником информации о курсе иностранной валюты выступают публикуемые центральным банком - эмитентом иностранной валюты значения валютного курса к доллару США.

Центр ценовых индексов оценивает валютные курсы иностранных валют, не публикуемые на сайте Банка России, посредством кросс-курсовых расчетов между курсом иностранной валюты к доллару США и курсом российского рубля к доллару США.

### Методика оценки кросс-курса

С целью определения курса валютной пары, напрямую не установленного Банком России и/или другими центральными банками, Центр ценовых индексов использует кросс-курсовые расчеты между валютными парами, курс которых достоверно определен.

Например, курс валютной пары MYR/RUB не публикуется Банком России на ежедневной основе, в таком случае для расчета обменного курса будут использованы курсы валютных пар USD/RUB и USD/MYR.

Оценка курса валютной пары с использованием кросс-курсовых расчетов осуществляется по следующей формуле:

$$
БВ/АВ=БВ/ПВ*ПВ/АВ,
$$

где:

БВ – базовая валюта, курс которой определен к альтернативной валюте;

АВ – альтернативная валюта, курс которой определен к промежуточной валюте;

ПВ – промежуточная валюта, курс которой определен как к базовой валюте, так и к альтернативной валюте.

### Оценка индексов в альтернативных валютах

В определенных случаях, если применимо, Центр ценовых индексов может публиковать информацию о ценовых индексах в альтернативных валютах, отличных от оригинальной валюты ценового индекса.

Конвертация в альтернативную валюту осуществляется с использованием среднего курса валютной пары оригинальной и альтернативной валют за период публикации ценового индекса по следующей формуле:

$$
Ц_АВ=Ц_ОВ*ОВ/АВ,
$$

где:

Ц_АВ – ценовой индекс, выраженный в альтернативной валюте;

Ц_ОВ – ценовой индекс, выраженный в оригинальной валюте;

ОВ/АВ – обменный курс валютной пары, выраженный в количестве альтернативной валюты за единицу оригинальной валюты.

### Корректировка данных

В случае необходимости исправления ошибочного значения ценового индикатора, возникшего вследствие технических сбоев, человеческой ошибки или некорректного применения принятой методологии, Центр ценовых индексов оставляет за собой право скорректировать данные.

Данные также могут быть скорректированы в случае исправления ошибок, возникших в результате сообщения участниками рынка не точной информации о сделках на рынке.

### Принципы формирования методологии и внесения изменений

Методологии разрабатываются и утверждаются независимым от блока оценки методологическим комитетом, который состоит из сотрудников, обладающих достаточным уровнем квалификации и профессиональным опытом.

В целях обеспечения актуальности, осуществляется ежегодная оценка соответствия методологии специфике рынка, необходимости упразднения неактуальных или создания новых ценовых индикаторов.

Центр ценовых индексов приветствует диалог с участниками рынка по вопросам методики, применяемой для оценки и формирования ценовых индикаторов.

Обновление методологии подразумевает подробное объяснение предлагаемых изменений и их обоснование.

Об изменении сообщается в соответствующем информационном продукте, также указывается дата, с которой изменения вступают в силу.

### Порядок хранения и использования информации

Центр ценовых индексов документирует и хранит:

-   Исходные данные, используемые при формировании ывлютных курсов;
-   Методологии, используемые при формировании валютных курсов;
-   Результаты расчета валютных курсов в соответствие с данной методологией.

### Конфиденциальность данных

Центр ценовых индексов придает большое значение обеспечению безопасности и защите информации, а также гарантирует полную конфиденциальность данных, получаемых от участников рынка.

## Спецификация

Курсы валют, публикуемые Банком России

| Валютная пара | Исходная методика расчета                                                                                   | Периодичность обновления |
|------------------|---------------------------|---------------------------|
| USD/RUB       | Средневзвешенный по объему торгов курс валюты, установленный на сделках, заключенных на межбанковском рынке | Ежедневно                |
| EUR/RUB       | Средневзвешенный по объему торгов курс валюты, установленный на сделках, заключенных на межбанковском рынке | Ежедневно                |
| CNY/RUB       | Средневзвешенный по объему торгов курс валюты, установленный на сделках, заключенных на Московской бирже    | Ежедневно                |

Курсы валют, публикуемые другими центральными банками

| Валютная пара | Исходная методика расчета                                                                                                | Периодичность обновления |
|------------------|---------------------------|---------------------------|
| USD/MYR       | Курс валюты, установленный на сделках, заключенных на межбанковском рынке в Куала-Лумпур на момент 11:30 (местное время) | Ежедневно                |

### Сроки проведения опроса

Ежемесячно
