---
title: "На Cbonds стартует размещение аналитики Центра ценовых индексов (21 октября 2024)"
date: 21/10/2024
lang: ru
---

## На Cbonds стартует размещение аналитики Центра ценовых индексов 

Москва, 21 октября 2024 г.

### Пресс-релиз


Cbonds (ООО «Сбондс.ру») и Центр ценовых индексов (АО «ЦЦИ») заключили соглашение о сотрудничестве. Теперь на платформе информационного агентства доступны 11 различных подписок на аналитические материалы, а также более 100 отраслевых индексов, которые отражают еженедельное изменение цен на товары российского сырьевого экспорта. Таким образом, у широкого круга российских компаний и экспертного сообщества появился доступ к данным о ценах на российские товары на отечественной информационной платформе. 

«Фрагментация товарных рынков снизила репрезентативность использования мировых ценовых бенчмарков на сырье для оценки стоимости товаров российского экспорта. Исторически так сложилось, что даже в тех отраслях, где Россия является основным маркет-мейкером, ценовые котировки считались в других географических регионах. Это не вызывало противоречий в эру глобализации, но сейчас создает информационную асимметрию, дополнительные риски и упущенные возможности для участников рынка. Размещение аналитики Центра ценовых индексов даст возможность пользователям получить оперативные и объективные данные о состоянии товарных рынков для принятия управленческих, налоговых, инвестиционных и бизнес-решений», — подчеркнули Наталья Порохова, Генеральный директор Центра ценовых индексов.

«Наше партнерство важный шаг по созданию в России собственного ресурса, на котором будет доступен широкий набор финансовых, экономических и ценовых индикаторов. Доступ к информации — важное конкурентное преимущество и развитие отечественных аналитических систем повышает устойчивость российского бизнеса в меняющихся условиях», - Ольга Штепа, Руководитель отдела товарных рынков Cbonds. 

Центр ценовых индексов (АО «ЦЦИ») — проект, покрывающий более 150 различных котировок в ключевых секторах экономики России. Репрезентативность ценовых котировок подтверждается участниками рынка.

Cbonds (ООО «Сбондс.ру») - информационное агентство, специализирующееся в сфере финансовых рынков. База данных Cbonds содержит свыше 80 000 индексов. Ресурс предлагает доступ к более чем 20 000 макроэкономическим показателям, собранным от мировых и российских агентств.

