---
title: "ЦЦИ начал публиковать индексы на фосфорсодержащие удобрения (20 января 2025)"
date: 20/01/2025
lang: ru
---

## ЦЦИ начал публиковать индексы на фосфорсодержащие удобрения


Москва, 20 января 2025 г.

### Пресс-релиз

С января 2025 г. Центр ценовых индексов начал публиковать ценовые индексы на сложные фосфорсодержащие удобрения: МАФ (моноаммонийфосфат) и ДАФ (диаммонийфосфат) на базисе FOB Baltic в [еженедельном отчете Минеральные удобрения](https://pbc-index.ru/markets/markets-fertilizers.html).

В мировом экспорте МАФ и ДАФ Россия занимает лидирующие позиции. В 2023 г. по экспорту МАФ на мировой рынок Россия заняла второе место после Марокко, по ДАФ – третье место, уступив Китаю и Марокко. В 2024 г. экспорт МАФ и ДАФ на мировые рынки российскими предприятиями составил около 4,8 млн т. По данным [консенсус-прогноза ЦЦИ](https://pbc-index.ru/forecasts/forecast-fertilizers.html) в 2025 г. экспортный объем увеличится на 4% до 5 млн т. 

Эксперты также говорят о том, что более быстрый рост спроса на фосфорные удобрения, чем ввод мощностей по их производству приведет к росту цен на фосфорсодержащие удобрения в долгосрочной перспективе до МАФ/ДАФ используются в качестве основного удобрения на любых типах почв для всех без исключения однолетних и многолетних полевых, овощных и плодовых культур как до их посева/посадки, так и при посеве/посадке. Главное предназначение фосфора – ускорение обменных процессов в клетках, и как следствие – более быстрый переход от цветения к плодоношению, лучшее вызревание семян и плодов, повышение сопротивляемости к заболеваниям. Наибольший эффект от удобрений наблюдается в системах питания на почвах с нейтральной и слабощелочной реакцией среды.