---
title: "Налоговая цена на нефть в макроконсенсусе ЦЦИ"
date: 30/01/2025
lang: ru
---

## Налоговая цена на нефть в макроконсенсусе ЦЦИ

30 января 2025 г.

### Пресс-релиз

В выпуске [макроконсенсуса](https://pbc-index.ru/forecasts/forecast-fx.html) Центра ценовых индексов (ЦЦИ) за январь 2025 г. включен новый показатель - **налоговая цена на нефть**. Налоговая цена на нефть - это экспортная цена на российскую нефть, определяемая в соответствие с нормами Налогового кодекса РФ и используемая для определения нефтегазовых налогов Федерального бюджета.

Налоговая цена на нефть связана с экспортными ценами на российскую нефть, но порядок ее расчета подвержен регуляторным изменениям. Так, с 1 января 2025 г. для определения налоговой цены на российскую нефть используется новая формула, включающая сразу несколько котировок российской нефти: Urals FOB Primorsk, Urals Med Aframax FOB Novorossiysk и ESPO blend FOB Kozmino. До данного изменения в 2024 г. использовались котировки Urals или North Sea Dated, уменьшенная на фиксированную величину.

Более подробно узнать о расчете налогвой цены и отслеживать ее динамику можно на [странице нефтяного рынка](http://pbc-index.ru/markets/markets-oil.html) сайта ЦЦИ.
