---
title: "ЦЦИ публикует первый консенсус-прогноз по рынку коммерческой недвижимости Санкт-Петербурга"
date: 05/02/2025
lang: ru
---

## ЦЦИ публикует первый консенсус-прогноз по рынку коммерческой недвижимости Санкт-Петербурга

5 февраля 2025 г.

### Пресс-релиз

Ежеквартальный консенсус-прогноз Центра ценовых индексов по рынку коммерческой недвижимости теперь доступен не только для Москвы, но и для Санкт-Петербурга. В первом для Северной столицы опросе приняли участие профессиональные аналитики 5 консалтинговых компаний, работающих в сфере коммерческой недвижимости, а именно: IBC Real Estate, IPG.Estate, Maris, NF Group, Nikoliers. 

Результаты показали, что ожидаются сравнительно низкие темпы роста арендных ставок на складском рынке Санкт-Петербурга и Ленинградской области и высокие темпы роста на офисном рынке города. Более подробно узнать о методологии и о будущей динамике складского и офисного рынков обеих столиц можно на [странице консенсус-прогноза](https://pbc-index.ru/forecasts/forecast-real-estate.html) по коммерческой недвижимости сайта ЦЦИ.

