---
title: "ЦЦИ запустил Котировку соевого шрота  (19 февраля 2026)"
date: 19/02/2025
lang: ru
---

</p>

## ЦЦИ запустил Котировку соевого шрота 

Москва, 19 Февраля 2026 г.

### Пресс-релиз

Центр ценовых индексов (ЦЦИ) начал рассчитывать ежемесячные котировки на соевый шрот (массовая доля сырого протеина - более 50%) на базисе FCA ЦФО. Котировки публикуются с января 2026 г. в ежемесячном отчете, который выходит каждую вторую среду месяца. 

«В России впервые появились ценовые котировки для соевого шрота. — комментирует Екатерина Захарова, старший аналитик ЦЦИ. — Котировка на соевый шрот ЦЦИ на базисе FCA ЦФО в феврале 2026 г. составила 32,7 тыс. руб., на 13% ниже января 2025 г. Цены на соевый шрот снижаются под давлением высокого предложения сои на рынке. Согласно опросу аграрных аналитиков, проведенному ЦЦИ в феврале 2026 г., прогноз валового сбора сои в России в 2025/26 г.  – 9 млн т, на 26,8% больше, чем в 2024/25 г. В 2026/27 г. ожидается коррекция вниз – до 8,4 млн т». 

На фоне роста производства растет и экспорт сои. По оценкам ЦЦИ в 2025 г. Россия впервые в истории стала нетто-экспортером сои. Импорт сои в Россию по оценкам ЦЦИ в 2025 г. составил не более 500 тыс. т сои. Общий объем экспорта сои из России в 2025 г. оценочно составил почти 700 тыс. т. 
Экспорт соевого шрота из России по данным OleoScope за первые четыре месяца 2025/26 г. составил 195 тыс. т, на 7% ниже соответствующего периода 2024/25 г. Республика Беларусь, крупнейший импортер соевого шрота из России, снизила импорт на 43% до 60 тыс. т. Поставки российского соевого шрота в Китай выросли в 4 раза до 16 тыс. т. 


[Спецификация внутренних цен на соевый шрот](../methodology/specs-soybeans.qmd)
