---
title: " ЦЦИ обновил методологию Сырьевого индекса (4 февраля 2026)"
date: 04/02/2025
lang: ru
---

</p>

## Металлы потеснили ТЭК: ЦЦИ обновил методологию Сырьевого индекса ЦЦИ в ответ на сдвиг в структуре российского экспорта

Москва, 4 Февраля 2026 г.

### Пресс-релиз

Центр ценовых индексов (ЦЦИ) представил обновленную версию Сырьевого индекса ЦЦИ. Снижение доли энергетического экспорта РФ до минимума за 5 лет потребовало увеличения представленности в индексе товаров неэнергетического экспорта.

В 2025 г. российский экспорт пережил структурный сдвиг. К ноябрю доля энергоносителей в экспортных доходах РФ сократилась до 52% - минимума, последний раз достигнутого в январе 2021 г. Перемены стали следствием мировой конъюнктуры сырьевых рынков - снижения цен на нефть при одновременном ценовом ралли в металлах. Медь подорожала на 47%, алюминий – на 54%, золото – на 80% с начала 2025 г.

Трансформация экспортных доходов РФ требует адекватного отражения в аналитических инструментах - ЦЦИ адаптировал структуру Сырьевого индекса ЦЦИ, увеличив охват сырьевого экспорта с 60 до 75%. Помимо широкого спектра ранее учитываемых цен на нефть, нефтепродукты, газ, уголь, пшеницу, подсолнечное масло и удобрения состав индекса дополнен ценами на черные, цветные и драгоценные металлы.

При снижении доходов РФ от энергетического экспорта на 16% в 2025 г., общие экспортные доходы сократились умереннее – на 5%. Быстрый рост цен на драгоценные металлы компенсировал до 70% падения цен на нефть. Для валютного рынка эффект роста цен на металлы был дополнен валютными интервенции по бюджетному правилу, которые сократили ослабление рубля от снижения цен на нефть на 2-3 руб./долл.

Расширение товаров-представителей в обновленной структуре Сырьевого индекса ЦЦИ повысит точность прогноза курса рубля в результате более объективной оценки экспортных доходов РФ. Сырьевой индекс ЦЦИ опережает данные о поступлении экспортной валютной выручки на 2 месяца.

Справка: Сырьевой индекс ЦЦИ рассчитывается еженедельно и отражает изменение цен на корзину сырьевых товаров российского экспорта с учетом их доли в структуре экспорта товаров из РФ, а также с учетом российской специфики экспортных цен, отличных от мировых.

[Подробнее об индексе](../pbc-index.qmd)
