name: Validate and Deploy Quarto Site

on:
  push:
    paths:
      - 'data/**'
      - 'py/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.4.550"
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("zoo", "TTR", "curl", "quantmod", "openxlsx", "tidyr", "xts", "dplyr", "highcharter"), repos="https://cloud.r-project.org")'

      - name: Run deploy script
        run: python py/data_deploy.py

        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
